import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Navbar from "../../src/components/common/navbar-main/page";
import Footer from "../../src/components/common/footer/page";

const lato = Lato({
    variable: "--font-lato",
    subsets: ["latin"],
    weight: ["100", "300", "400", "700", "900"]
});

export const metadata: Metadata = {
    title: "Area - Koseeker",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${lato.variable}`} suppressHydrationWarning>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
