import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Navbar from "../components/navbar_main/page";
import Footer from "../components/footer/page";

const lato = Lato({
    variable: "--font-lato",
    subsets: ["latin"],
    weight: ["100", "300", "400", "700", "900"]
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
            <html lang="en">
            <body className={`${lato.variable}`}>
                <Navbar/>
                {children}
                <Footer/>
            </body>
        </html>
    );
}
