import Footer from "../../src/components/common/footer/page"
import Navbar from "../../src/components/common/navbar-main/page"

export const metadata = {
    title: 'Home Page',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <div>
            <Navbar />
            {children}
            <Footer />
        </div>
    )
}

export default RootLayout